/*
 * SendGUI.java
 *
 * Created on 2010/4/12, 上午 05:45:36
 */

package fileexchange;
import java.io.*;
import javax.swing.*;
/**
 *
 * @author StarryDawn
 */
public class SendGUI extends javax.swing.JFrame {

    /** Creates new form SendGUI */
    public SendGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("傳送檔案");
        setMinimumSize(new java.awt.Dimension(227, 117));

        jLabel1.setFont(new java.awt.Font("微軟正黑體", 0, 12));
        jLabel1.setText("傳送檔案");

        jButton1.setText("OK");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("微軟正黑體", 0, 12));
        jLabel2.setText("檔案大小:");

        jLabel3.setFont(new java.awt.Font("微軟正黑體", 0, 12));
        jLabel3.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		this.setVisible(false);
	}//GEN-LAST:event_jButton1ActionPerformed

	public File getFile() {
		JFileChooser fc = new JFileChooser();
		int result = fc.showOpenDialog(new JFrame());
		File sendfile;
		if (result == JFileChooser.APPROVE_OPTION) {
			sendfile = fc.getSelectedFile();
			filename = sendfile.getAbsolutePath();
			filesize = (int)sendfile.length();
			jLabel1.setText("傳送檔案" + filename);
			jLabel2.setText("大小: "+filesize+" bytes");
			jLabel3.setText("等待對方接收...");
			return sendfile;
		}
		else return null;
	}

	public void send() {
		jLabel1.setText("傳送檔案" + filename );
		jLabel2.setText("大小: "+filesize+" bytes");
		jLabel3.setText("傳送中...");
	}
	public void done() {
		jLabel3.setText("傳送完成！");
		jButton1.setEnabled(true);
	}
	public void denyTransfer() {
		JOptionPane.showMessageDialog(this, "對方拒絕接收檔案", "", JOptionPane.INFORMATION_MESSAGE);
	}

	private String filename;
	private int filesize;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
